# fly.toml file generated for yomochikunbot on 2023-02-28T10:44:13+09:00

app = "yomochikunbot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
