# fly.toml app configuration file generated for yomochikunbot on 2023-08-26T19:42:42+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yomochikunbot"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  PORT = "8080"
